name: Build and Test ReadyGap
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PROXY_PORT: 8080
      TEST_TIMEOUT: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install dependencies
        run: go mod download

      - name: Build application
        run: go build -v -o ready-gap .

      - name: Start ReadyGap proxy server
        id: proxy
        run: |
          ./ready-gap -addr :$PROXY_PORT &
          echo "PROXY_PID=$!" >> $GITHUB_OUTPUT

      - name: Install curl for testing
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Make test requests through proxy
        run: |
          export http_proxy=http://localhost:$PROXY_PORT
          export https_proxy=http://localhost:$PROXY_PORT
          curl google.com
          curl example.com
          curl github.com
          
      - name: Stop proxy server and generate reports
        run: |
          echo "Stopping proxy server..."
          kill ${{ steps.proxy.outputs.PROXY_PID }}
          sleep 2

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ready-gap-reports
          path: |
            sites_dump.json
            sites_report.html
          retention-days: 7